### ISSUE TITLE
Odd behaviour with smeltery casts

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#10]
After creating a new cast, I'd have to remove the cast and replace it on the casting table in order to pour metals into the cast. Without first removing it, I was unable to pour.

Casts this has affected so far- ingot, gear, plate
Metals used so far- iron, bronze

I'm not sure if this is something you'd be able to fix on your own.

**Comment by Drakma** [comment]
Unable to reproduce
