### ISSUE TITLE
String wisp production is low

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#11]
Math time!

On average I've been getting 1 wisp per queen, with 2qty occasionally and even zero rarely. Each generation takes 2 minutes 10 seconds from start to finish at 0.00769 string wisps per second. You need 3 to create a normal string and 9 to make a woven silk. 24 pieces of woven silk simply to create your apiarist armor means 216 string wisps for a total average time of 7.8 hours, divided by the number of apiaries running string bees.

Our current options are to cripple your entire production and breeding to run string bees in all your apiaries, or vastly expand your apiary section with over a dozen apiaries and expend many early-game resources.

Suggestion- increase the quantity dropped to 2, or possibly 3 with some testing.

**Comment by Drakma** [comment]
Doubled the chance for silk to drop.  Will leave open for testing.

**Comment by Drakma** [comment]
Testing showed improved drop rates
