### ISSUE TITLE
Suggestion- replace meta-quests with multi-step quests

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#13]
Apiarist's Protection meta-quest doesn't auto-complete quest parts as you create each armor piece. I had to unequip all pieces before it would detect and complete the quest. I suspect this is because the meta-quest requires the previous 4 to be complete before it will activate. Instead of 4 quests plus the final quest with the same requirements, I suggest a single quest that checks off each task as it's performed. The single item quests currently don't give any rewards and are redundant.

**Comment by Drakma** [comment]
Quests for multiple items has been streamlined.  It will complete as it progresses
