### ISSUE TITLE
Bug- zombie bees do not produce rotten flesh

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#14]
Several generations have not dropped any rotten flesh and bees do not appear in JEI as a source for them. Typo in configs?

**Comment by Drakma** [comment]
Doubled drop rate.  It was set to 8% now set to 15%

**Comment by Drakma** [comment]
wrong item name was used was. "minecraft:flesh" instead of "minecraft:rotten_flesh"
