### ISSUE TITLE
Suggestion- Nether Wart Bees drop rates & quest

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#22]
Current drop rates:
15% I:minecraft:nether_wart@0
10% I:minecraft:brown_mushroom@0
5% I:minecraft:red_mushroom@0
10% I:forestry:honey_drop@0

I think the mushrooms should have a smaller drop chance, since they are a tertiary drop and not needed in large quantities.

Also, the quest requires 6x Nether Wart Blocks, which comes out to 54 nether warts. All the other bee quests (except fire/water bees) require just 6 of the main item. As this bee has a slightly higher drop rate for it's main resource, I think 2 nether wart blocks would be closer to the other quests.

**Comment by Drakma** [comment]
Changed in latest build
