### ISSUE TITLE
portal can't be created when you update / world corrup

### ISSUE THREAD

**Issue by alurio22** [Drakma/vacant-sky-3#23]
hi , when i try to make a portal for everending sun , i use the stick whith right click and it doesn't works .
the cause for me (i supposed) : i made my world on 3.0.1 and update my modpack , now im on 3.1.0.3 and i can't created the portal because my world is "corrupted"
i try a new world on the same version , and the portal can be open , so the update of the modpack broke my save.
ty for reply and your works

**Comment by Drakma** [comment]
I am unable to reproduce this.  I upgraded an old version to the latest and both existing and new portals worked.
