### ISSUE TITLE
Deep Freeze too cold for Cold bees

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#24]
The Deep Freeze is an icy climate and too cold for cold climate bees. When you first arrive there you don't have the resources necessary to create and power alvearies in any dimension yet.

**Comment by karsen777** [comment]
If this is intended and the player should be using frame upgrades, I suggest adding it to the quest descriptions.

**Comment by Drakma** [comment]
Biomes o Plenty changed the temps of some of their biomes.  I have updated the bees to work in their respective dimensions again.
