### ISSUE TITLE
Coal Logs not dropping as intended

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#28]
When converting logs into coal logs using Botania's Pure Daisy, they are converted correctly. However, when breaking the logs the mechanics for Sky Orchards jump in and appropriately break the coal logs into normal logs and coal resin, meaning you will never be able to get coal logs without a silk touch tool.

**Comment by karsen777** [comment]
As this goes for all log types, the Livingwood recipes also require a silk touch tool to progress as it is the only way to get the required logs.

**Comment by Drakma** [comment]
What do you need coal logs for?  You take the resin to form amber to make the coal sapling.

Yes, you'll need silk touch for the other logs.  That's the point.
