### ISSUE TITLE
Zen Summoning Recipes need to be added

### ISSUE THREAD

**Issue by Drakma** [Drakma/vacant-sky-3#36]

**Comment by karsen777** [comment]
I have tried 5 or 6 of the new summoning recipes and all of them give the message "The altar is unsatisfied" when right-clicking with the stick. I've verified that the items used are the same ones in JEI.

![unsatisfied](https://user-images.githubusercontent.com/25237568/58378474-42b4dc00-7f49-11e9-9851-e45b3b7fd0a9.png)
