### ISSUE TITLE
Inferium Sapling outputs aren't used for anything specific

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#38]
While you can create Inferium Saplings, neither the acorns nor resin can be used to craft anything. The remaining drops are logs, sticks, leaves, and saplings that can be used for any generic recipe, but otherwise this sapling is currently useless.

**Comment by Drakma** [comment]
Whoops, You'll be able to dehydrate amber for the essence

**Comment by Drakma** [comment]
Added in latest build
