### ISSUE TITLE
Incorrect recipe for Iron Seeds

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#44]
The Botania recipe for Iron Seeds in the Runic Altar is incorrect and doesn't display the required iron bars.

**Comment by karsen777** [comment]
Saltpeter Seeds also have an incorrect recipe and require Pulverized Iron instead of Niter (saltpeter).

**Comment by karsen777** [comment]
Blaze Seeds are missing a Runic Altar recipe completely.

Thorium, Boron, Lithium, and Magnesium Seeds have an additional smeltery recipe that bypasses the expensive Runic Altar recipe and should be removed.

Diamond Seeds are lacking an Avaritia recipe.

Uranium and Iridium Seeds have a smeltery recipe that lets you bypass the Avaritia recipe.

**Comment by Drakma** [comment]
All Fixed in latest build.
