### ISSUE TITLE
Duplication bug with infusion crystals

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#52]
Infusion crystals used in recipes to craft the next tier are not being used up. I've tested with both full charges and empty charges with similar results. I tested within a crafting table as well as the Simple Storage Network Storage Request Table and Upgraded Storage Remote with same results.

**Comment by Drakma** [comment]
Working as intended

https://github.com/Electrolyte220/MysticalAgricultureTieredCrystals/issues/3
