### ISSUE TITLE
Acorns still drop from manually grown and chopped trees

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#53]
If you grow a sapling as usual, using bonemeal or just waiting, you can break the leaves and acorns drop. Since you need to silk touch logs for Botania, you'll always encounter acorns this way.

**Comment by Drakma** [comment]
This is an issue with the mod.  Unfortunately I can't do anything with them.

**Comment by karsen777** [comment]
I believe you can change it in the Sky Orchards config- config/sky_orchards.cfg, line 59. If it does not then I am out of ideas and we'll just live with it.
