### ISSUE TITLE
Environmental Tech crystals drop from incorrect Void Miner tiers

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#60]
Except for the tier 1 crystal Litherite that has a Botania recipe, the other crystals come from the void miner tiers that also require them to craft that tier's controller. Each crystal needs to be shifted down a tier so that Erodium is mined from tier 1 controllers, Kyronite from tier 2, etc. The final tier's crystal Lonsdaleite currently cannot be obtained.

**Comment by Drakma** [comment]
Fixed
