### ISSUE TITLE
YABBA Hammer/Painter quests have incorrect names

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#61]

**Comment by Drakma** [comment]
Uh no?

**Comment by karsen777** [comment]
These belong in the quest description but are not good titles.

![titles](https://user-images.githubusercontent.com/25237568/58678226-c9840300-8313-11e9-9e49-3c410dc657e8.png)

**Comment by Drakma** [comment]
They’re perfectly fine where they are
