### ISSUE TITLE
Cobble Bee Quest text & description

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#9]
All other bee quests are titled with the bee's name, but cobble is called "Breed a Cobble Bee" instead of "Cobble Bee." Also, in the description, "mutated" should read "mutate."

I would change "Wood bees are one of these types" so something like "Cobble Bees randomly mutate from Wood Bees" to clear up confusion, as it's referencing a different bee without naming the cobble bee.

**Comment by Drakma** [comment]
Fixed in latest build
